version: '3'

services:

  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      #- .:/code
      - .:/app
    #network_mode: host
    depends_on:
      - mongo
      - elastic
    command: python run.py

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    depends_on:
      - mongo
#volumes:
#  data:
