version: '3'

services:
  #mongo:
  #  image: mongo
  #  container_name: mongo
  #  environment:
  #    - MONGO_DATA_DIR=/data/db
  #    - MONGO_LOG_DIR=/dev/null
  #  volumes:
  #    - ./data/mongo:/data/db
  #  ports:
  #      - 27018:27017
  app:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
